#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

#define WINDOW_POSITION_X 100
#define WINDOW_POSITION_Y 200
#define WINDOW_SIZE_X 700
#define WINDOW_SIZE_Y 350
#define PLAY_GROUND_SIZE_X 35
#define PLAY_GROUND_SIZE_Y 35
#define PLAY_GROUND_SIZE_W 630
#define PLAY_GROUND_SIZE_H 280
#define FIRST_PLAYER_X PLAY_GROUND_SIZE_X
#define FIRST_PLAYER_Y (PLAY_GROUND_SIZE_H-PLAYER_PAD_H)/2 + PLAY_GROUND_SIZE_X
#define SECOND_PLAYER_X PLAY_GROUND_SIZE_X+PLAY_GROUND_SIZE_W-PLAYER_PAD_W
#define SECOND_PLAYER_Y (PLAY_GROUND_SIZE_H-PLAYER_PAD_H)/2 + PLAY_GROUND_SIZE_X
#define PLAYER_PAD_W 10
#define PLAYER_PAD_H 100
#define PLAYER_PAD_MOVE 10
#define BALL_W 10
#define BALL_H 10
#define BALL_X (PLAY_GROUND_SIZE_W-BALL_W)/2 + PLAY_GROUND_SIZE_X
#define BALL_Y (PLAY_GROUND_SIZE_H-BALL_H)/2 + PLAY_GROUND_SIZE_Y
#define BALL_VELOCITY_X 6
#define BALL_VELOCITY_Y 6
#define AI_ON_OFF true // true - on, false - off
#define AI_level 100 // от 1 до 100#define PATH_TO_FONTFILE "ASMAN.ttf"#define RESULT_X WINDOW_SIZE_X/2-10
#define RESULT_Y 15

#endif // CONST_H_INCLUDED
